version: 2
jobs:
  build:
    environment:
      CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
    docker:
    - image: testim/docker-cli
    steps:
      - run: mkdir -p /tmp/testim/
      - run: testim --token $TESTIM_PROJECT --project $TESTIM_PROJECT --grid $TESTIM_GRID --report-file /tmp/testim/results.xml
      - store_artifacts:
          path: /tmp/circleci-test-results
      - store_test_results:
          path: /tmp/circleci-test-results
