version: 2.1
workflows:
  my-workflow:
    jobs:
      - build:
          context:
            - deriv

jobs:
  build:
    docker:
    - image: testim/docker-cli
    steps:
      - run: mkdir -p /tmp/testim/
      - run: testim --token $TESTIM_PROJECT --project $TESTIM_PROJECT --grid $TESTIM_GRID --report-file /tmp/testim/results.xml
      - store_artifacts:
          path: /tmp/circleci-test-results
      - store_test_results:
          path: /tmp/circleci-test-results
