version: 2
jobs:
  build:
    docker:
    - image: testim/docker-cli
    steps:
      - run: mkdir -p /tmp/testim/
      - run: testim --token $PROJECT --project $PROJECT --grid $GRID --report-file /tmp/testim/results.xml
      - store_artifacts:
          path: /tmp/circleci-test-results
      - store_test_results:
          path: /tmp/circleci-test-results
